<ul class="breadcrumb">
	<li class="parent"><a href="/manager/client">Clients</a></li>
	<li class="title"><a href="/manager/client/edit/id/<?php echo $this->client->getId();?>"><?php echo $this->client->getName();?></a></li>
	<li class="title"><?php echo $this->employee->getFirstName();?>  <?php echo $this->employee->getLastName();?></li>
</ul>


<table border="1">
<thead>
	<tr>
        <th>Date</th>

        <th>Type</th>
		<th>Amount</th>
		<th>Deduction</th>
		<th>Cut-off</th>
		<th>Balance</th>
        <th>Notes</th>

		<th>Actions</th>
	</tr>
</thead>
<tbody>
	<?php if(count($this->deductions) > 0): ?>
	<?php foreach($this->deductions as $value) : ?>
	<tr>
        <td><?php if($value->getDateAdded() != '0000-00-00 00:00:00') { echo date('M d, Y h:i A', strtotime($value->getDateAdded())); }?></td>
		<td><?php echo ucwords(str_replace('_', ' ', $value->getType()))?></td>
		<td>P <?php echo number_format($value->getAmount(),2);?></td>
		<td>P <?php echo number_format($value->getDeduction(),2);?></td>
		<td>
			<?php if($value->getCutOff() == '1'): ?>
				1-15
			<?php elseif($value->getCutOff() == '2'): ?>
				16-31
			<?php elseif($value->getCutOff() == '3'): ?>
				Both
			<?php endif;?>
		</td>
		<td><?php echo number_format($value->getAmount() - $this->deducted_amounts[$value->getId()],2); ?></td>
        <td><?php echo $value->getNotes();?></td>

		<td><a href="/manager/deduction/edit/id/<?php echo $value->getId();?>">Edit</a></td>
	</tr>
	<?php endforeach; ?>
	<?php else: ?>
	<tr>
		<td colspan="6">No deductions</td>
	</tr>
	<?php endif; ?>
</tbody>
</table>
<?php echo $this->form; ?>

<br /><br />