<div style="margin: 0 auto; width: 80%;">
<h3>I am sorry. But something went horribly wrong.</h3>
<!--<h2><?php echo $this->message ?></h2>-->

<?php if (isset($this->exception)): ?>

    <!--<h3>Exception information:</h3>-->
    <h2 style="border-radius: 5px; background-color: crimson; text-align: center; color: antiquewhite">
        <?php echo $this->exception->getMessage() ?>
    </h2>

    <blockquote style="font-size: 0.8em; color: #ccc;overflow: auto;">
        <pre><?php echo $this->exception->getTraceAsString() ?></pre>
        <!--
        <h3>Request Parameters:</h3>
        <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?></pre>
        -->

    </blockquote>
<?php endif ?>
