<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
  <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
  <title>Zend Framework Default Application</title>
</head>
<body>
  <h2 class="button alert">I am sorry.  But something went horribly wrong.</h2>
  <!--<h2><?php echo $this->message ?></h2>-->

  <?php if (isset($this->exception)): ?>
  
  <!--<h3>Exception information:</h3>-->
  <p>
      <!--<b>Message:</b>--> <?php echo $this->exception->getMessage() ?>
  </p>

    <blockquote style="font-size: 0.8em; color: #ccc; width: 80%; overflow: auto;">
  <p>Stack trace:</p>
  <pre><?php echo $this->exception->getTraceAsString() ?>
  </pre>

  <h3>Request Parameters:</h3>
  <pre><?php echo $this->escape(var_export($this->request->getParams(), true)) ?>
  </pre>
    </blockquote>
  <?php endif ?>

</body>
</html>
