<dl>
    <dd><a href="<?php echo $this->api_host ?>/api/accrual/silp" class="button">SILP cutoff-to-date</a></dd>
    <dd><a href="<?php echo $this->api_host ?>/api/accrual/silp?atd=true" class="button">SILP anniversary-to-date</a></dd>
    <dd><a href="<?php echo $this->api_host ?>/api/accrual/thirteenth-month" class="button">13th month cutoff-to-date</a></dd>
    <dd><a href="<?php echo $this->api_host ?>/api/accrual/thirteenth-month?atd=true" class="button">13th month anniversary-to-date</a></dd>
</dl>