<table class="table">
    <tr>
        <th></th>
        <th>Client-group</th>
        <th>Rider</th>
        <th></th>
    </tr>
    <?php $i = 0;
    foreach ($this->anomalies as $anomaly): $i++; ?>
        <tr class="anomaly-list <?php if ($anomaly->is_approved == 1): ?>disabled<?php endif; ?>"
            data-anomaly-id="<?= $anomaly->id ?>">
            <td><?= $i; ?> <?= $anomaly->id ?></td>
            <td>
                <a href="/dataentry/attendance/employee/id/<?= $anomaly->employee_id;
                ?>/date_start/<?= $this->payroll_dates->start;
                ?>/date_end/<?= $this->payroll_dates->end;
                ?>/group_id/<?= $anomaly->group_id;
                ?>/pay_period/<?= $this->payroll_dates->period;
                ?>" target="_blank"><?= $anomaly->group->fullname; ?></a>
            </td>
            <td><?= $anomaly->employee->name; ?></td>
            <td class="<?php if ($anomaly->is_approved == 1): ?>approved<?php endif; ?>">
                <button class="button tiny secondary uncheck">Uncheck</button>
                <button class="button tiny check">Checked</button>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
<script>
    $(function () {
        $('.check-buttons').each(function () {
            console.log($(this).html());
        });

        $('.check').on('click', function () {
            $(this).parent().addClass('approved');
            var parent_tr = $(this).parents('.anomaly-list:first');
            parent_tr.addClass('disabled');

            $.post('/payroll/index/update-dtr-anomaly',
                {
                    anomaly_id: parent_tr.data('anomaly-id'),
                    is_approved: 1
                }
            );
        });

        $('.uncheck').on('click', function () {
            $(this).parent().removeClass('approved');
            var parent_tr = $(this).parents('.anomaly-list:first');
            parent_tr.removeClass('disabled');

            $.post('/payroll/index/update-dtr-anomaly',
                {
                    anomaly_id: parent_tr.data('anomaly-id'),
                    is_approved: 0
                }
            );
        });
    });
</script>
<style>
    .anomaly-list.disabled {
        opacity: 0.3
    }

    .anomaly-list .uncheck {
        display: none;
    }

    .anomaly-list .approved .check {
        display: none;
    }

    .anomaly-list .approved .uncheck {
        display: block;
    }


</style>