<h4>Pay period: <?php echo $this->period_covered; ?> to <?php echo $this->period_end; ?></h4>
<dl>
    <dd><a href="/payroll/index/etps/period_covered/<?php echo $this->period_covered; ?>" class="button">ETPS</a></dd>

    <dd>
        Riders with sub-1k salary
        <table class="table">
            <thead>
            <tr>
                <th>Period covered</th>
                <th>ETPS date/time processed</th>
            </tr>
            </thead>
            <tbody>
            <?php foreach ($this->etps_report_1k as $sub_etps): ?>
                <tr>
                    <td><a href="<?= $sub_etps['link'] ?>"><?= $sub_etps['period'] ?></a></td>
                    <td><?= $sub_etps['date'] ?></td>
                </tr>
            <?php endforeach; ?>
            </tbody>
        </table>
    </dd>
    <?php // if (date('d', strtotime($this->period_covered)) == '16') : ?>
        <dd>
            <a href="/payroll/index/philhealth/period_covered/<?php echo $this->period_covered; ?>" class="button">Philhealth</a>
            <a href="/payroll/index/hdmf/period_covered/<?php echo $this->period_covered; ?>" class="button">HDMF</a>
            <a href="/payroll/index/sss/period_covered/<?php echo $this->period_covered; ?>" class="button">SSS</a>
        </dd>
    <?php // endif; ?>
    <dd><a href="/payroll/index/export/period_covered/<?php echo $this->period_covered; ?>" class="button">Payroll
            report</a></dd>

</dl>

<div class="thin-round-border" style="border: 1px solid #eee; border-radius: 5px;">

    <ul class="tabs" data-tab>
        <li class="tab-title active"><a href="#panel1">Bill-to-Messerve OT</a></li>
        <li class="tab-title"><a href="#panel2">Rest day duty</a></li>
        <li class="tab-title"><a href="#panel3">Short duty</a></li>
        <li class="tab-title"><a href="#panel4">No duty for the last 2 months</a></li>
    </ul>
    <div style="margin: 0 10px;">
        <div class="tabs-content">
            <div class="content active" id="panel1">
                <div class="messerve-ot">
                    <table class="table">
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="content" id="panel2">
                <div class="rest-day-duty">
                    <table class="table">
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="content" id="panel3">
                <div class="short-duty">
                    <table class="table">
                        <tbody></tbody>
                    </table>
                </div>
            </div>
            <div class="content" id="panel4">
                <div class="no-duty">
                    <table class="table">
                        <tbody></tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

<h4>Old payroll reports</h4>
<div
        style="margin-left: 1.0em; font-size: 0.8em; height: 200px; overflow-y: auto; border: 1px solid #aaa; padding: 10px; border-radius: 5px; width: 200px;">
    <dl>
        <?php foreach ($this->old_periods as $period): ?>
            <dd>
                <a href="/payroll/index/export/period_covered/<?php echo $period; ?>"><?php echo $period; ?></a>
            </dd>
        <?php endforeach; ?>
    </dl>
</div>
<script>
    $(function () {
        $.get('<?php echo $this->api_host; ?>/api/report/messerve-ot', function (data) {
            var short_duty = $('.messerve-ot tbody');
            if (!data.length > 0) {
                short_duty.append('<tr><td>None</td></tr>');
            } else {
                for (var i in data) {
                    var css = 'unapproved';

                    if (data[i].approved == 'yes') {
                        css = 'approved';
                    }
                    short_duty.append('<tr class="' + css + '"><td>' + data[i].group + ' </td><td> '
                        + data[i].rider + ' (' + data[i].employee_number + ') </td><td>  '
                        + data[i].ot_hours + ' Hour/s </td><td>' + data[i].date + '</td><td><a target="_blank" href="' + data[i].link + '">View attendance</a></td></tr>');
                }

                short_duty.append('<tr><td colspan="5"><a href="<?php echo $this->api_host; ?>/api/report/messerve-ot?download=oh-yes">Download report</a></td></tr>');
            }
        });

        $.get('<?php echo $this->api_host; ?>/api/report/no-duty', function (data) {
            var no_duty = $('.no-duty tbody');
            if (!data.length > 0) {
                no_duty.append('<tr><td>None</td></tr>');
            } else {
                for (var i in data) {
                    no_duty.append('<tr><td>' + data[i].group + ' </td><td> ' + data[i].rider + ' (' + data[i].employee_number + ') </td></tr>');
                }
            }
        });

        $.get('<?php echo $this->api_host; ?>/api/report/short-duty', function (data) {
            var short_duty = $('.short-duty tbody');
            if (!data.length > 0) {
                short_duty.append('<tr><td>None</td></tr>');
            } else {
                for (var i in data) {
                    short_duty.append('<tr><td>' + data[i].group + ' </td><td> '
                        + data[i].rider + ' (' + data[i].employee_number + ') </td><td>  '
                        + data[i].duty + ' Hours </td></tr>');
                }

            }
        });


        $.get('<?php echo $this->api_host; ?>/api/report/rest-day-duty', function (data) {
            var rest_day_duty = $('.rest-day-duty tbody');
            if (!data.length > 0) {
                rest_day_duty.append('<tr><td>None</td></tr>');
            } else {
                for (var i in data) {
                    rest_day_duty.append('<tr><td>' + data[i].group + ' </td><td> ' + data[i].rider + ' (' + data[i].employee_number + ')</td></tr>');
                }
            }
        });
    });
</script>