<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <title>Messerve</title>

    <link href="<?php echo $this->baseUrl(); ?>/css/cssreset-min.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/cssbase-min.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/cssfonts-min.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/cssgrids-min.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/icons.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/messerve.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/smoothness/jquery-ui-1.9.0.custom.min.css" type="text/css" rel="stylesheet" />
    <!-- <link href="http://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet" type="text/css">-->

    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.2.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.9.0.custom.min.js"></script>

</head>
<body class="<?php
echo Zend_Controller_Front::getInstance()->getRequest()->getModuleName(); ?> <?php
echo Zend_Controller_Front::getInstance()->getRequest()->getControllerName(); ?> <?php
if(Zend_Controller_Front::getInstance()->getRequest()->getControllerName() != Zend_Controller_Front::getInstance()->getRequest()->getActionName())
    echo Zend_Controller_Front::getInstance()->getRequest()->getActionName(); ?>">

<div id="main" class="yui3-g">
    <div class="yui3-u-1" >
        <div class="yui3-u-1" id="content">
            <?php // preprint($this->user_auth); ?>
            <dl class="hor-menu">

                <?php if($this->user_auth): ?>
                    <dd><a href="/dataentry/attendance">Attendance</a></dd>
                    <!--
				<dd>You are logged in as <strong><?php echo $this->user_auth->real_name; ?></strong></dd>
				<dd><a href="/auth/changepass">Change password</a></dd>
				<dd><a href="/auth/logout">Logout</a></dd>-->
                <?php else: ?>

                    <dd><a href="/auth/login">Login</a></dd>
                <?php endif;?>
            </dl>

            <br clear="all" />
            <br clear="all" />

            <?php echo $this->layout()->content; ?>
        </div>
    </div>
</div>
<br clear="all" /><br />
<div style="background-color: #fea; border: 1px solid #999; width: 100%; position: fixed; bottom:0px; padding: 10px; margin-top: 10px; margin-bottom: 0;">


    <dl class="hor-menu">
        <dd><em>Messerve Payroll System 0.2.1 (BOP Rollout Version)</em></dd>
        <?php if($this->user_auth): ?>
            <dd>You are logged in as <strong><?php echo $this->user_auth->real_name; ?></strong></dd>
            <dd><a href="/auth/changepass">Change password</a></dd>
            <dd><a href="/auth/logout">Logout</a></dd>
        <?php else: ?>
            <dd><a href="/auth/login">Login</a></dd>
        <?php endif;?>
    </dl>

</div>

<script type="text/javascript">
    <!--
    $(function() {


    } );
    //-->
</script>
</body>
</html>