<!DOCTYPE html>
<html class="iframe">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>Servitor - frame</title>

    <link rel="stylesheet" href="/css/normalize.css">
    <link rel="stylesheet" href="/css/foundation.css">
    <link rel="stylesheet" href="/css/foundation-icons.css" />

    <link href="<?php echo $this->baseUrl(); ?>/css/messerve.css" type="text/css" rel="stylesheet" />
    <link href="<?php echo $this->baseUrl(); ?>/css/smoothness/jquery-ui-1.9.0.custom.min.css" type="text/css" rel="stylesheet" />

    <script src="/js/vendor/modernizr.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-1.8.2.js"></script>
    <script src="/js/foundation.min.js"></script>
    <script type="text/javascript" src="<?php echo $this->baseUrl(); ?>/js/jquery-ui-1.9.0.custom.min.js"></script>

</head>
<body>
<?php echo $this->layout()->content; ?>
<script type="text/javascript">
<!--
    $(document).foundation();
	$(function() { 
		$('.datepicker').datepicker( { changeYear: true, dateFormat: 'yy-mm-dd' } );
		$('.ui-button').button();
    } );
//-->
</script>
</body>
</html>